services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-money_manager}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    expose:
      - "9000"
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  caddy_data:
  caddy_config:
